export enum API_LIST {
  REGISTER = 'registration/register',
  LOGIN = 'registration/login',
  LOGOUT = 'registration/logout',
  GET_ALL_USERS = 'users',
  GET_ROLE_FILTER = 'roles/filter',
  ORGANIZATIONS = 'organizations',
  ORGANIZATION_ONBOARD = 'organizations/onboard',
  ORGANIZATION_FILTER = 'organizations/filter',
  SERVICES = 'services',
  SERVICES_RESULT = 'services/result',
  FACTOR_SIGNATURE = 'services/factor-signature',
  SERVICES_ACTIVITIES = 'services/activities',
  FACILITIES = 'facilities',
  EMISSION_FACTORS = 'emission-factors',
  EMISSION_FACTORS_FILTER = 'emission-factors/filter',
  INVENTORY_ENTRIES = 'inventory-entries',
  INVENTORY_ENTRIES_FILTER = 'inventory-entries/filter',
  UPLOAD_INVENTORY_DOC = 'inventory-entries/upload-document',

  // Master Configuration APIs
  MASTERS_SIDEBAR_STRUCTURE = 'masters/sidebar-structure',
  MASTERS_TYPE_SCHEMA = 'masters/types/:code/schema',
  MASTERS_SUPPORTED_TYPES = 'masters/supported-types',
  MASTERS_ITEMS = 'masters/items',
  MASTERS_ITEMS_FILTER = 'masters/items/filter',
  MASTERS_ITEMS_BULK_IMPORT = 'masters/items/bulk-import',
  MASTERS_MATRIX_EXPORT = 'masters/matrix/export',
  MASTERS_UNIT_CONVERSIONS = 'masters/unit-conversions',
  MASTERS_UNIT_CONVERT = 'masters/unit-conversions/convert',
  MASTERS_GAS_TYPES = 'masters/gas-types',
  MASTERS_GWP_VERSIONS = 'masters/gwp-versions',
  MASTERS_FACTOR_SETS = 'masters/factor-sets',
  MASTERS_FORMULAS = 'masters/formulas',
  MASTERS_POLICIES = 'masters/policies',
  MASTERS_SUPPLEMENTARY_FIELDS = 'masters/supplementary-fields',

  // Enterprise Scale APIs
  ENTERPRISE_TENANTS = 'enterprise/tenants',
  ENTERPRISE_API_KEYS = 'enterprise/api-keys',
  ENTERPRISE_WEBHOOKS = 'enterprise/webhooks',
  ENTERPRISE_AUDIT_LOGS = 'enterprise/audit-logs',
}
