export enum API_LIST {
  REGISTER = 'registration/register',
  LOGIN = 'registration/login',
  LOGOUT = 'registration/logout',
  GET_ALL_USERS = 'users',
  GET_ROLE_FILTER = 'roles/filter',
  ORGANIZATIONS = 'organizations',
  ORGANIZATION_ONBOARD = 'organizations/onboard',
  ORGANIZATION_FILTER = 'organizations/filter',
  SERVICES = 'services',
  FACILITIES = 'facilities',
  EMISSION_FACTORS = 'emission-factors',
  EMISSION_FACTORS_FILTER = 'emission-factors/filter',
  INVENTORY_ENTRIES = 'inventory-entries',
  INVENTORY_ENTRIES_FILTER = 'inventory-entries/filter',
  UPLOAD_INVENTORY_DOC = 'inventory-entries/upload-document',
}
