import { Scope3CategoryType, Scope3CategoryConfig } from '@/types/inventory';

export type { Scope3CategoryType, Scope3CategoryConfig };

export const SCOPE3_CONFIGS: Record<string, Scope3CategoryConfig> = {
  'Purchased Goods and Services': {
    title: 'Purchased Goods and Services',
    categoryTag: 'Purchased Goods and Services',
    subType: 'purchased_goods',
    defaultUnit: 'kg',
    formulaLabel: 'Mass/Spend × Emission Factor',
    descriptionText: 'Upstream emissions from extraction, production, and transportation of goods and services purchased or acquired.',
    noteText: 'Note: Collect supplier-specific emissions data or spend-based EEIO emission factors.',
  },
  'Capital Goods': {
    title: 'Capital Goods',
    categoryTag: 'Capital Goods',
    subType: 'capital_goods',
    defaultUnit: 'USD',
    formulaLabel: 'Capital Expenditure × EEIO Factor',
    descriptionText: 'Final products that have an extended life and are used by the company to manufacture products, provide services, or store, sell, and transport merchandise.',
    noteText: 'Note: Categorize capital assets by type (equipment, machinery, buildings) and report in the year of acquisition.',
  },
  'Fuel- and Energy-Related Activities': {
    title: 'Fuel- and Energy-Related Activities',
    categoryTag: 'Fuel- and Energy-Related Activities',
    subType: 'energy_activities',
    defaultUnit: 'kWh',
    formulaLabel: 'Energy Consumed × Well-To-Tank (WTT) Factor',
    descriptionText: 'Emissions related to the production of fuels and energy purchased and consumed by the reporting company that are not included in Scope 1 or Scope 2.',
    noteText: 'Note: Includes upstream emissions of purchased fuels, T&D losses, and generation of purchased electricity sold to end users.',
  },
  'Upstream Transportation and Distribution': {
    title: 'Upstream Transportation & Distribution',
    categoryTag: 'Upstream Transportation and Distribution',
    subType: 'upstream_transportation',
    defaultUnit: 'tonne.km',
    formulaLabel: '(Weight in tonnes × Distance in km) × Emission Factor',
    descriptionText: 'Transportation and distribution of products purchased by the reporting company in the reporting year between Tier 1 suppliers and its own operations.',
    noteText: 'Note: Mode of transport (road, rail, air, sea) significantly alters emission factor values.',
  },
  'Waste Generated in Operations': {
    title: 'Waste Generated in Operations',
    categoryTag: 'Waste Generated in Operations',
    subType: 'waste_generated',
    defaultUnit: 'kg',
    formulaLabel: 'Waste Weight × Treatment Emission Factor',
    descriptionText: 'Emissions from third-party disposal and treatment of waste generated in the reporting company’s operations.',
    noteText: 'Note: Differentiate between landfill, incineration, recycling, composting, and anaerobic digestion.',
  },
  'Business Travel': {
    title: 'Business Travel',
    categoryTag: 'Business Travel',
    subType: 'business_travel',
    defaultUnit: 'pkm',
    formulaLabel: 'Passenger km / Spend × Travel Emission Factor',
    descriptionText: 'Emissions from transportation of employees for business-related activities in vehicles owned or operated by third parties.',
    noteText: 'Note: Includes air travel (short/long haul), rail, taxi, rental cars, and hotel stays.',
  },
  'Employee Commuting': {
    title: 'Employee Commuting',
    categoryTag: 'Employee Commuting',
    subType: 'employee_commuting',
    defaultUnit: 'pkm',
    formulaLabel: '(Employees × Avg Distance × Days) × Mode Emission Factor',
    descriptionText: 'Emissions from transportation of employees between their homes and their worksites, including teleworking.',
    noteText: 'Note: Survey employee commuting habits or use average regional commuting statistics.',
  },
  'Upstream Leased Assets': {
    title: 'Upstream Leased Assets',
    categoryTag: 'Upstream Leased Assets',
    subType: 'upstream_leased',
    defaultUnit: 'm2',
    formulaLabel: 'Floor Area / Energy Consumed × Building EF',
    descriptionText: 'Emissions from the operation of assets leased by the reporting company in the reporting year, not included in Scope 1 or Scope 2.',
    noteText: 'Note: Apply operational control criteria to determine if leased assets belong in Scope 1/2 or Scope 3.',
  },
  'Downstream Transportation and Distribution': {
    title: 'Downstream Transportation & Distribution',
    categoryTag: 'Downstream Transportation and Distribution',
    subType: 'downstream_transportation',
    defaultUnit: 'tonne.km',
    formulaLabel: '(Weight in tonnes × Distance in km) × Transport EF',
    descriptionText: 'Transportation and distribution of products sold by the reporting company in the reporting year between operations and end consumers.',
    noteText: 'Note: Includes storage in third-party warehouses and distribution centers.',
  },
  'Processing of Sold Products': {
    title: 'Processing of Sold Products',
    categoryTag: 'Processing of Sold Products',
    subType: 'processing_sold',
    defaultUnit: 'kg',
    formulaLabel: 'Mass of Intermediate Product × Processing EF',
    descriptionText: 'Emissions from processing of sold intermediate products by third-party manufacturers prior to use by the end consumer.',
    noteText: 'Note: Applicable if sold products require further chemical or physical transformation.',
  },
  'Use of Sold Products': {
    title: 'Use of Sold Products',
    categoryTag: 'Use of Sold Products',
    subType: 'use_sold',
    defaultUnit: 'units',
    formulaLabel: '(Units Sold × Lifetime Fuel/Electricity × EF)',
    descriptionText: 'Emissions from the use of goods and services sold by the reporting company over their expected lifetime.',
    noteText: 'Note: Differentiate between direct use-phase emissions (e.g., fuel-consuming goods) and indirect use-phase emissions.',
  },
  'End-of-Life Treatment of Sold Products': {
    title: 'End-of-Life Treatment of Sold Products',
    categoryTag: 'End-of-Life Treatment of Sold Products',
    subType: 'end_of_life',
    defaultUnit: 'kg',
    formulaLabel: 'Mass of Sold Products × Waste Stream Disposal EF',
    descriptionText: 'Emissions from the waste disposal and treatment of products sold by the reporting company at the end of their lifetime.',
    noteText: 'Note: Estimate average product composition and regional waste management proportions (recycled vs landfilled).',
  },
  'Downstream Leased Assets': {
    title: 'Downstream Leased Assets',
    categoryTag: 'Downstream Leased Assets',
    subType: 'downstream_leased',
    defaultUnit: 'm2',
    formulaLabel: 'Leased Area × Building Intensity EF',
    descriptionText: 'Emissions from operation of assets owned by reporting company and leased to third parties in reporting year.',
    noteText: 'Note: Report emissions if not included in Scope 1 or Scope 2 under equity share approach.',
  },
  'Franchises': {
    title: 'Franchises',
    categoryTag: 'Franchises',
    subType: 'franchises',
    defaultUnit: 'units',
    formulaLabel: 'Franchise Count / Floor Area × Average Facility EF',
    descriptionText: 'Emissions from the operation of franchises in the reporting year, not included in Scope 1 or Scope 2.',
    noteText: 'Note: Includes emissions from franchisee building energy, refrigerants, and operational activities.',
  },
  'Investments': {
    title: 'Investments',
    categoryTag: 'Investments',
    subType: 'investments',
    defaultUnit: 'USD',
    formulaLabel: 'Investment Amount × (Investee Emissions / Investee Value)',
    descriptionText: 'Emissions associated with the reporting company’s investments in the reporting year, including equity, debt, and project finance.',
    noteText: 'Note: Categorize according to PCAF (Partnership for Carbon Accounting Financials) asset class guidelines.',
  },
};
