const APP_NAME = "OMEA-ADM";

const URS_ID = {
    LOGIN:'02',
    SITE_RESOURCES: '011',
    SYSTEM_INTEGRATION: '004',
    ROOM_INTEGRATION: '005',
    ALL_USERS: '006',
    USER_ROLES: '007',
    WORKFLOW_CUSTOMIZATION: '009',

}

const SRS_ID = {
    LOGIN: `${URS_ID.LOGIN}-038`,
    ALL_USERS: `${URS_ID.ALL_USERS}-013`,
    SITE_RESOURCES: `${URS_ID.SITE_RESOURCES}-016`,
    SYSTEM_INTEGRATION: `${URS_ID.SYSTEM_INTEGRATION}-017`,
    CREATE_USER: `${URS_ID.USER_ROLES}-024`,
    USER_ROLES: `${URS_ID.USER_ROLES}-028`,
    USERS_TABLE: `${URS_ID.USER_ROLES}-034`,
    ROOM_INTEGRATION: `${URS_ID.ROOM_INTEGRATION}-041`,
    ACTION_TEMPLATE: `${URS_ID.WORKFLOW_CUSTOMIZATION}-043`,
    PROTOCOL_CHECKBOX: `${URS_ID.WORKFLOW_CUSTOMIZATION}-043`,
    ADD_WORKFLOW: `${URS_ID.WORKFLOW_CUSTOMIZATION}-043`,
    DUPLICATE_TEMPLATE: `${URS_ID.WORKFLOW_CUSTOMIZATION}-043`,
    DIAGNOSTIC_VIEW: `${URS_ID.WORKFLOW_CUSTOMIZATION}-043`,
    WORKFLOW_CARD: `${URS_ID.WORKFLOW_CUSTOMIZATION}-045`,
    WORKFLOW_CUSTOMIZATION_PAGE: `${URS_ID.WORKFLOW_CUSTOMIZATION}-045`,
    WORKFLOW_LIST_SIDEBAR: `${URS_ID.WORKFLOW_CUSTOMIZATION}-045`,
    ANATOMY_LIST: `${URS_ID.WORKFLOW_CUSTOMIZATION}-045`,
}

function generateTestId(srsNo: string, testNo: number): string {
    const paddedTestNo = testNo.toString().padStart(2, '0');
    return `${APP_NAME}-${srsNo}-UTC-${paddedTestNo}`;
}

export {
    APP_NAME,
    URS_ID,
    SRS_ID,
    generateTestId
}
